<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'Can not bind this ID many times..' => '',
    'Email' => '',
    'Group Course Unit Start Time' => '班的课时开始时间',
    'ID' => '',
    'Invalid name or this student does not exists.' => '',
    'Invalid name or this teacher does not exists.' => '',
    'Openid' => '',
    'Openid Owner ID' => '',
    'Subcourse ID' => '子课程ID',
    'Teacher Name' => '教师姓名',
    'Addr' => '地址',
    'Bind successfully' => '绑定成功！',
    'Birthday' => '生日',
    'Body URL' => '全身像',
    'Can not bind this ID many times' => '同一ID不能多次绑定！',
    'Cat' => '类型',
    'Caution' => '注意事项',
    'Comment' => '评语',
    'Course ID' => '课程ID',
    'Course Schedule ID' => '课时计划ID',
    'Course Unit ID' => '课时ID',
    'Course Unit Is Over' => '课时制定完毕',
    'Create Time' => '创建时间',
    'Delete' => '删除',
    'Delete reserve, are you sure?' => '删除预约，确定？',
    'Des' => '简介',
    'Feature' => '特色',
    'Gh ID' => '公号ID',
    'Group ID' => '班ID',
    'GroupStudent ID' => '学生ID',
    'Head URL' => '头像',
    'History' => '发展历程',
    'Identify ID' => '身份证',
    'Invalid name or this student id does not exists.' => '姓名无效或学生ID不存在。',
    'Invalid name or this teacher id does not exists.' => '姓名无效或老师ID不存在。',
    'Is Delete' => '删除',
    'Is Repay' => '是否补课',
    'Is Signon' => '已签到',
    'Latitude' => '纬度',
    'Logo Url' => 'Logo图片地址',
    'Longtitude' => '经度',
    'Minutes' => '时长(分钟)',
    'Mobile' => '联系电话',
    'Name' => '姓名',
    'Nationality' => '国籍',
    'Object' => '目标',
    'Onboard Time' => '入职时间',
    'Owner Cat' => '所有者类型',
    'Owner ID' => '所有者ID',
    'Parent ID' => '父母ID',
    'Photo ID' => '图片ID',
    'Photo Owner ID' => '所有者ID',
    'Pic Url' => '图片链接',
    'Prepare' => '准备',
    'Qq' => 'QQ',
    'Room ID' => '教室ID',
    'School Branch ID' => '校区ID',
    'School ID' => '学校ID',
    'Score' => '成绩',
    'Sex' => '性别',
    'Signon ID' => '签到ID',
    'Size' => '大小',
    'Slogan' => '口号',
    'Sort Order' => '序号',
    'Start Time' => '开始时间',
    'Status' => '状态',
    'Student ID' => '学生ID',
    'Tags' => '标签',
    'Target Student' => '目标人群',
    'Teacher ID' => '教师ID',
    'Title' => '标题',
    'Unbind' => '解除绑定',
    'Unbind this ID, are you sure?' => '解除绑定, 确定？',
    'Update Time' => '更新时间',
    'Website' => '网址',
    'recommend successfully' => '推荐成功',
    'reserve successfully' => '预约成功',
];
