<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'Active' => '',
    'Administrator' => '',
    'Alias' => '',
    'Author' => '',
    'Body' => '',
    'Caption' => '',
    'Carousel ID' => '',
    'Category' => '',
    'Comment' => '',
    'Config' => '',
    'Created At' => '',
    'Created at' => '',
    'Deleted' => '',
    'E-mail' => '',
    'Firstname' => '',
    'Gender' => '',
    'ID' => '',
    'Key' => '',
    'Lastname' => '',
    'Manager' => '',
    'Middlename' => '',
    'Order' => '',
    'Path' => '',
    'Picture' => '',
    'Published' => '',
    'Published At' => '',
    'Role' => '',
    'Slug' => '',
    'Status' => '',
    'Title' => '标题',
    'Updated At' => '',
    'Updater' => '',
    'Url' => '',
    'User' => '',
    'User ID' => '',
    'Username' => '',
    'Value' => '',
    '{attribute} must be a valid JSON' => '',
];
