<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'About' => '',
    'Account' => '',
    'Articles' => '',
    'Backend' => '',
    'Check your email for further instructions.' => '',
    'Contact' => '',
    'Create' => '',
    'E-mail' => '',
    'Error while oauth process.' => '',
    'Female' => '',
    'Home' => '',
    'If you forgot your password you can reset it <a href="{link}">here</a>' => '',
    'Incorrect username or password.' => '',
    'Language' => '',
    'Log in with' => '',
    'Login' => '',
    'Logout' => '',
    'Male' => '',
    'Need an account? Sign up.' => '',
    'New password was saved.' => '',
    'Page not found' => '',
    'Password' => '',
    'Password reset for {name}' => '',
    'Profile' => '',
    'Request password reset' => '',
    'Reset password' => '',
    'Sign up with' => '',
    'Signup' => '',
    'Sorry, we are unable to reset password for email provided.' => '',
    'This email address has already been taken.' => '',
    'This username has already been taken.' => '',
    'Update' => '',
    'Username' => '',
    'Username or email' => '',
    'We already have a user with email {email}' => '',
    'Welcome to {app-name}. Email with your login information was sent to your email.' => '',
    'Your profile has been successfully saved' => '',
    '{app-name} | Your login information' => '',
];
