<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'Addr' => '',
    'Bind successfully' => '',
    'Birthday' => '',
    'Body URL' => '',
    'Can not bind this ID many times' => '',
    'Can not bind this ID many times..' => '',
    'Cat' => '',
    'Caution' => '',
    'Comment' => '',
    'Course ID' => '',
    'Course Schedule ID' => '',
    'Course Unit ID' => '',
    'Course Unit Is Over' => '',
    'Create Time' => '',
    'Delete' => '',
    'Delete reserve, are you sure?' => '',
    'Des' => '',
    'Email' => '',
    'Feature' => '',
    'Gh ID' => '',
    'Group Course Unit Start Time' => '',
    'Group ID' => '',
    'GroupStudent ID' => '',
    'Head URL' => '',
    'History' => '',
    'ID' => '',
    'Identify ID' => '',
    'Invalid name or this student does not exists.' => '',
    'Invalid name or this student id does not exists.' => '',
    'Invalid name or this teacher does not exists.' => '',
    'Invalid name or this teacher id does not exists.' => '',
    'Is Delete' => '',
    'Is Repay' => '',
    'Is Signon' => '',
    'Latitude' => '',
    'Logo Url' => '',
    'Longtitude' => '',
    'Minutes' => '',
    'Mobile' => '',
    'Name' => '',
    'Nationality' => '',
    'Object' => '',
    'Onboard Time' => '',
    'Openid' => '',
    'Openid Owner ID' => '',
    'Owner Cat' => '',
    'Owner ID' => '',
    'Parent ID' => '',
    'Photo ID' => '',
    'Photo Owner ID' => '',
    'Pic Url' => '',
    'Prepare' => '',
    'Qq' => '',
    'Room ID' => '',
    'School Branch ID' => '',
    'School ID' => '',
    'Score' => '',
    'Sex' => '',
    'Signon ID' => '',
    'Size' => '',
    'Slogan' => '',
    'Sort Order' => '',
    'Start Time' => '',
    'Status' => '',
    'Student ID' => '',
    'Subcourse ID' => '',
    'Tags' => '',
    'Target Student' => '',
    'Teacher ID' => '',
    'Teacher Name' => '',
    'Title' => '',
    'Unbind' => '',
    'Unbind this ID, are you sure?' => '',
    'Update Time' => '',
    'Website' => '',
    'recommend successfully' => '',
    'reserve successfully' => '',
];
